Churras/Controllers/ChurrasController.cs
using ChurrasTrinca.Models;
using Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChurrasTrinca.Controllers
{
    public class ChurrasController : Controller
    {
        private readonly ChurrasDB churrasDB;
        private readonly ParticipanteDB partDB;

        public ChurrasController()
        {
            churrasDB = new ChurrasDB(new ChurrasEntities());
            partDB = new ParticipanteDB();
        }

        // GET: Churras
        public ActionResult Index()
        {
            var churras = new List<ChurrasListModel>();

            var dados = churrasDB.ListarChurras();

            churras.AddRange(
                from c in dados
                select new ChurrasListModel()
                    {
                        Id = c.Id,
                        Data = c.Data,
                        Descricao = c.Motivo,
                        NumeroParticipantes = churrasDB.Participantes(c.Id),
                        TotalArrecadado = churrasDB.TotalArrecadado(c.Id)
                    });
            return View(churras);
        }

        // GET: Churras/Details/5
        public ActionResult Details(int id)
        {
            var model = new ChurrasDetailsModel();

            var churras = churrasDB.BuscarChurras(id);
            var part = partDB.ListarParticipantesChurras(id);

            model.Id = churras.Id;
            model.Motivo = churras.Motivo;
            model.Observacao = churras.Observacao;
            model.Data = churras.Data;
            model.ValorBebida = churras.ValorComBebida ?? 0;
            model.ValorSemBebida = churras.ValorSemBebida ?? 0;

            model.Participantes = churrasDB.Participantes(id);         
            model.Bebem = churrasDB.Bebuns(id);
            model.NaoBebem = churrasDB.NaoBebuns(id);
            model.ValorArrecadado = churrasDB.TotalArrecadado(id);
            model.ValorPago = churrasDB.ValorPago(id);
            
            return View(model);
        }

        // GET: Churras/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Churras/Create
        [HttpPost]
        public ActionResult Create(ChurrasCreateModel model)
        {
            try
            {

                churrasDB.IncluirChurras(
                    model.Data,
                    model.Motivo,
                    model.Observacao,
                    model.ValorBebida,
                    model.ValorSemBebida
                    );

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Churras/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Churras/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Add(int id)
        {
            return RedirectToAction("Edit/"+ id, "Participante");
        }

        public ActionResult ListaParticipante(int id)
        {
            return RedirectToAction("Details/"+ id, "Participante");
        }

        // GET: Churras/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Churras/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Churras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Under Domme</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Os churras da Galera", "Index", "Churras", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Temperatura", "ControlList", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Os churras da Galera</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>